apiVersion: v1
kind: Service
metadata:
  name: soap-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: soap-pod
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: soap-replica
  labels:
    app: soap-replica
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: soap-pod
    spec:
      containers:
      - name: soap-container
        image: igalonso/soap-example
        ports:
        - containerPort: 8000
          protocol: TCP